POST http://localhost:9000/api/
content-type: application/json

{
  "program": "Arnold's Golden Six",
  "day": "Day 1",
  "date": "2022-10-11T12:53:12.831Z",
  "movements": [
    {
      "name": "Deadlift",
      "sets": [
        {
          "weight": "100",
          "amountOfReps": "8"
        },
        {
          "weight": "100",
          "amountOfReps": "8"
        },
        {
          "weight": "100",
          "amountOfReps": "8"
        }
      ]
    },
    {
      "name": "Bench Press",
      "sets": [
        {
          "weight": "80",
          "amountOfReps": "8"
        },
        {
          "weight": "80",
          "amountOfReps": "8"
        },
        {
          "weight": "80",
          "amountOfReps": "8"
        }
      ]
    }
  ]
}